name: WDAN
description: "Web developer apprentice network"
baseurl: /curriculum
url: https://mongy352.github.io
exclude: ['yarn.lock', 'node_modules', 'LICENSE', 'package.json', 'Gemfile', 'Gemfile.lock', '.gitignore']